# .prettierrc
printWidth: 120
singleQuote: true
tabWidth: 2
trailingComma: 'all'
bracketSpacing: true
arrowParens: 'avoid'
overrides:
  - files: '*.json'
    options:
      parser: 'json'
  - files: '*.ts'
    options:
      parser: 'typescript'
      semi: true
